### ISSUE TITLE
list를 볼때

### ISSUE THREAD

**Issue by hy-kiera** [Ramenseller/B4_OS18#13]
due가 지난 것과 지나지 않은 것, 전체(지난것+지나지 않은것)을 선택해서 볼 수 있는 옵션을 추가하면 좋을 거 같은데, 어느 부분에 추가하면 좋을까요?

**Comment by Goodkorning** [comment]
list 함수에 추가되는게 좋을거 같습니다

**Comment by ujma1234** [comment]
list에서 만들어도 되고 처음에 a,l,m,q 부분에 setting을 추가해서 뷰 옵션을 넣어도 괜찮을 것 같네요

**Comment by hy-kiera** [comment]
@ujma1234 list함수에 파라미터로 전달하는 건가요?
