### ISSUE TITLE
due를 체크해서 자동으로 finished되는 기능

### ISSUE THREAD

**Issue by hy-kiera** [Ramenseller/B4_OS18#21]
실행시킬때 due를 체크해서 시스템시간과 비교해 지난 todo를 자동으로 finished되게 만든다.

**Comment by ujma1234** [comment]
시스템 시간을 가져오는 기능이 있나요?

**Comment by hy-kiera** [comment]
@ujma1234 python time 모듈에서 시스템 시간을 가져오는 함수가 있던거로 기억해요. datatime, timestamp...

**Comment by ujma1234** [comment]
I'll take it

**Comment by hy-kiera** [comment]
add todo에서 due를 입력할 때 현재 시간(날짜)보다 이전으로 선언하는 것을 막는 기능도 생기면 좋을 거 같아요
